/*
 * atoms.hxx
 *
 *  Created on: 26 févr. 2011
 *      Author: gschwind
 */

#ifndef ATOMS_HXX_
#define ATOMS_HXX_

#include <X11/Xatom.h>

namespace page {

#define DEFINE_ATOM(name) char const * const name = #name;

DEFINE_ATOM(ATOM);
DEFINE_ATOM(CARDINAL);
DEFINE_ATOM(WINDOW);
DEFINE_ATOM(UTF8_STRING);

DEFINE_ATOM(WM_STATE);
DEFINE_ATOM(WM_NAME);
DEFINE_ATOM(WM_DELETE_WINDOW);
DEFINE_ATOM(WM_PROTOCOLS);
DEFINE_ATOM(WM_TAKE_FOCUS);

DEFINE_ATOM(WM_NORMAL_HINTS);
DEFINE_ATOM(WM_CHANGE_STATE);

DEFINE_ATOM(WM_HINTS);

DEFINE_ATOM(_NET_SUPPORTED);
DEFINE_ATOM(_NET_WM_NAME);
DEFINE_ATOM(_NET_WM_STATE);
DEFINE_ATOM(_NET_WM_STRUT_PARTIAL);
DEFINE_ATOM(_NET_WM_STRUT);

DEFINE_ATOM(_NET_WM_WINDOW_TYPE);

DEFINE_ATOM(_NET_WM_WINDOW_TYPE_DESKTOP);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_DOCK);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_TOOLBAR);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_MENU);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_UTILITY);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_SPLASH);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_DIALOG);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_DROPDOWN_MENU);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_POPUP_MENU);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_TOOLTIP);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_NOTIFICATION);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_COMBO);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_DND);
DEFINE_ATOM(_NET_WM_WINDOW_TYPE_NORMAL);

DEFINE_ATOM(_NET_WM_USER_TIME);

DEFINE_ATOM(_NET_CLIENT_LIST);
DEFINE_ATOM(_NET_CLIENT_LIST_STACKING);

DEFINE_ATOM(_NET_NUMBER_OF_DESKTOPS);
DEFINE_ATOM(_NET_DESKTOP_GEOMETRY);
DEFINE_ATOM(_NET_DESKTOP_VIEWPORT);
DEFINE_ATOM(_NET_CURRENT_DESKTOP);
DEFINE_ATOM(_NET_WM_DESKTOP);

DEFINE_ATOM(_NET_SHOWING_DESKTOP);
DEFINE_ATOM(_NET_WORKAREA);

DEFINE_ATOM(_NET_ACTIVE_WINDOW);

DEFINE_ATOM(_NET_WM_STATE_MODAL);
DEFINE_ATOM(_NET_WM_STATE_STICKY);
DEFINE_ATOM(_NET_WM_STATE_MAXIMIZED_VERT);
DEFINE_ATOM(_NET_WM_STATE_MAXIMIZED_HORZ);
DEFINE_ATOM(_NET_WM_STATE_SHADED);
DEFINE_ATOM(_NET_WM_STATE_SKIP_TASKBAR);
DEFINE_ATOM(_NET_WM_STATE_SKIP_PAGER);
DEFINE_ATOM(_NET_WM_STATE_HIDDEN);
DEFINE_ATOM(_NET_WM_STATE_FULLSCREEN);
DEFINE_ATOM(_NET_WM_STATE_ABOVE);
DEFINE_ATOM(_NET_WM_STATE_BELOW);
DEFINE_ATOM(_NET_WM_STATE_DEMANDS_ATTENTION);
DEFINE_ATOM(_NET_WM_STATE_FOCUSED);

DEFINE_ATOM(_NET_WM_ALLOWED_ACTIONS);
DEFINE_ATOM(_NET_WM_ACTION_MOVE);
DEFINE_ATOM(_NET_WM_ACTION_RESIZE);
DEFINE_ATOM(_NET_WM_ACTION_MINIMIZE);
DEFINE_ATOM(_NET_WM_ACTION_SHADE);
DEFINE_ATOM(_NET_WM_ACTION_STICK);
DEFINE_ATOM(_NET_WM_ACTION_MAXIMIZE_HORZ);
DEFINE_ATOM(_NET_WM_ACTION_MAXIMIZE_VERT);
DEFINE_ATOM(_NET_WM_ACTION_FULLSCREEN);
DEFINE_ATOM(_NET_WM_ACTION_CHANGE_DESKTOP);
DEFINE_ATOM(_NET_WM_ACTION_CLOSE);
DEFINE_ATOM(_NET_WM_ACTION_ABOVE);
DEFINE_ATOM(_NET_WM_ACTION_BELOW);

DEFINE_ATOM(_NET_CLOSE_WINDOW);

DEFINE_ATOM(_NET_REQUEST_FRAME_EXTENTS);
DEFINE_ATOM(_NET_FRAME_EXTENTS);

DEFINE_ATOM(_NET_WM_ICON);

DEFINE_ATOM(_NET_WM_PID);

DEFINE_ATOM(WM_TRANSIENT_FOR);

DEFINE_ATOM(PAGE_QUIT);

DEFINE_ATOM(_NET_SUPPORTING_WM_CHECK);

DEFINE_ATOM(_NET_DESKTOP_NAMES);


}

#endif /* ATOMS_HXX_ */
