/*
 * cairo_surface_type_name.hxx
 *
 * copyright (2010-2014) Benoit Gschwind
 *
 * This code is licensed under the GPLv3. see COPYING file for more details.
 *
 */

#ifndef CAIRO_SURFACE_TYPE_NAME_HXX_
#define CAIRO_SURFACE_TYPE_NAME_HXX_

namespace page {

static char const * const cairo_surface_type_name[] = {
    "CAIRO_SURFACE_TYPE_IMAGE",
    "CAIRO_SURFACE_TYPE_PDF",
    "CAIRO_SURFACE_TYPE_PS",
    "CAIRO_SURFACE_TYPE_XLIB",
    "CAIRO_SURFACE_TYPE_XCB",
    "CAIRO_SURFACE_TYPE_GLITZ",
    "CAIRO_SURFACE_TYPE_QUARTZ",
    "CAIRO_SURFACE_TYPE_WIN32",
    "CAIRO_SURFACE_TYPE_BEOS",
    "CAIRO_SURFACE_TYPE_DIRECTFB",
    "CAIRO_SURFACE_TYPE_SVG",
    "CAIRO_SURFACE_TYPE_OS2",
    "CAIRO_SURFACE_TYPE_WIN32_PRINTING",
    "CAIRO_SURFACE_TYPE_QUARTZ_IMAGE",
    "CAIRO_SURFACE_TYPE_SCRIPT",
    "CAIRO_SURFACE_TYPE_QT",
    "CAIRO_SURFACE_TYPE_RECORDING",
    "CAIRO_SURFACE_TYPE_VG",
    "CAIRO_SURFACE_TYPE_GL",
    "CAIRO_SURFACE_TYPE_DRM",
    "CAIRO_SURFACE_TYPE_TEE",
    "CAIRO_SURFACE_TYPE_XML",
    "CAIRO_SURFACE_TYPE_SKIA",
    "CAIRO_SURFACE_TYPE_SUBSURFACE",
    "CAIRO_SURFACE_TYPE_COGL"
};

}

#endif /* CAIRO_SURFACE_TYPE_NAME_HXX_ */
